Repository n0-computer/sendme, pull requests merged in 2023-02, with the labels that each got.

#100 fix: ensure CI runs on main
  .github/workflows/ci.yml
Labels: bug, ci

#97 feat: pass in custom names for blobs
  src/main.rs
  src/provider.rs
Labels: feature

#140 fix(ci): run clippy directly
  .github/workflows/ci.yml
Labels: bug, ci, fix

#139 fix: fail if an on_blob function does not read all the content
  src/get.rs
  src/lib.rs
Labels: fix

#141 feat: Add generic progress emitter utility
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/progress.rs
Labels: feature

#143 Fix QUIC stream completion
  src/protocol.rs
  src/provider.rs
Labels: bug

#150 fix: ensure we emit `TransferAborted` event if anything goes wrong during the transfer
  src/lib.rs
  src/progress.rs
  src/provider.rs
Labels: fix

#135 feat: netsim CI
  .github/workflows/netsim.yml
Labels: ci, perf
